import Head from "next/head";
import classes from "../styles/Home.module.scss";
import AllBlogs from "../components/AllBlogs/AllBlogs";


async function getPosts() {
  const res = await fetch("https://api.nelta.de/articles").then((res) =>
    res.json()
  );
  return res;
}

export const getStaticProps = async ({ params }) => {
  const posts = await getPosts();
  return {
    props: { posts },
  };
};

export default function Home(props) {
  const { posts } = props;

  return (
    <div className={classes.container}>
      <Head>
        <title>Project01</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ul className={classes.ul}>
          {posts.map((post) => {
            return <AllBlogs post={post} />;
          })}
        </ul>
      </main>
    </div>
  );
}
